version: '3.8'

services:
  redis:
    image: redis:alpine
    command: redis-server
    hostname: redies
    ports:
      - "6379:6379"

  api:
    image: api
    build:
      context: ./backend/GameDaOld
      dockerfile: ./GameDaOld.UI.Api/Dockerfile
    environment:
      - ConnectionStrings__Redis=redis:6379
      #- ASPNETCORE_URLS=http://+:5023
    ports:
      - "5023:8080"
    depends_on:
      - redis
  
  nuxt_app:
    image: nuxt_app
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    environment:
      - NUXT_PUBLIC_URL_SIGNALR=http://localhost:5023/JogoDaVelhaHub
    ports:
      - "3000:3000"
    
